### ISSUE TITLE
Extend the Provider interfaces

### ISSUE THREAD

**Issue by howardjohn** [howardjohn/Kitchen-Companion#52]
Right now there are 3 provider classes, Recipe, Ingredients, and Comments. These currently provide an interface for read access to the database. They should be expanded to allow reading and writing. With writing, "Provider" is probably a good name, so they should probably be renamed to something like [RecipeDAO](https://en.wikipedia.org/wiki/Data_access_object).

**Comment by willyim123** [comment]
I'm going to create DAO classes for the 3 provider classes so Brian can work on the database query portion right now, but we can change the "Provider" classes to [BLL classes](https://en.wikipedia.org/wiki/Business_logic) that call the DAO classes. This is so we can decouple the logic a bit more.

The structure for calls should look like this:
API BLL -> DAO -> database

Anthony, you can still work on this issue, but instead of "RecipeDAO", you can change it to "RecipeBLL".
